### ISSUE TITLE
Discussion: async support for AuthHandler 

### ISSUE THREAD

**Issue by Charles-Schleich** [webrtc-rs/turn#12]
Hello,

I am wondering about the `auth_handle` function inside the `AuthHandler` trait and whether or not it makes sense to potentially make it an async function using [async-trait](https://crates.io/crates/async-trait).

My rational behind wanting this is that if the struct that you implement `AuthHandler` for has a `RwLock` / `Mutex` it would make more sense to use the `RwLock` / `Mutex` that comes from your async framework, rather than  `std::sync::*`, and it would be more ergonomic to `.await` on it rather than spawning a blocking task from a non async function.

If the user wants to add or remove usernames and passwords from elsewhere in the code also within the context of an async function, potentially this turn server is generating or receiving username password combos.

While i have not gone very deep into async Rust, i have read in a couple of places that warn against using `std::sync::{RwLock}` in certain scenarios
https://docs.rs/tokio/latest/tokio/sync/struct.Mutex.html#which-kind-of-mutex-should-you-use, but it will also depend on what is being done with the lock.

So if any of the authors of the library feel that it makes sense for `auth_handle` to be an async function then i'm happy to implement it and submit a PR.

**Comment by k0nserv** [comment]
We have migrated this crate to the monorepo([webrtc-rs/webrtc](https://github.com/webrtc-rs/webrtc/)) please re-open this issue over there.
